# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-16 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='Description about this location.'),
            preserve_default=False,
        ),
    ]
